name: in_app_purchase_example
description: Demonstrates how to use the in_app_purchase plugin.
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  in_app_purchase: ^3.0.2
    # When depending on this package from a real application you should use:
    #   in_app_purchase: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
   # path: ../
  shared_preferences: ^2.0.0

dev_dependencies:
  flutter_driver:
    sdk: flutter

  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
